# Site settings
title: hack.commit.push
email: organization@hack-commit-pu.sh
description: |
  hack.commit.push
  Paris JUNE 15, 2019
  The 1st hackergarten conference
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: hackcommitpush
github_username:

# Build settings
markdown: kramdown
