# Site settings
title: hack.commit.push
email: organization@hack-commit-pu.sh
description: |
  hack.commit.push
  Paris JUNE 15, 2019
tagline: One Day to Contribute to Open Source
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
default_lang: "en"

twitter_username: hackcommitpush
github_username:
github_url: https://github.com/hackergarten/Paris2019
youtube_channel: https://www.youtube.com/channel/UCMTI7EciSV3AF_g_NjvMg0A
# Build settings
markdown: kramdown
